__inline('../vendor/jquery/1.12.3/jquery.min.js')
__inline('../vendor/classnames/2.2.3/index.min.js')
__inline('../vendor/react/0.14.8/react.js')
__inline('../vendor/react/0.14.8/react-dom.min.js')
__inline('../vendor/rem_layout/rem.js')
